# Generated by Django 3.0.5 on 2020-05-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('com_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('com_type', models.CharField(choices=[('RAW AGRICULTURAL', 'RAW AGRICULTURAL'), ('PROCESSED', 'PROCESSED')], db_column='com-type', default='RAW AGRICULTURAL', max_length=16)),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'List of our Commodities',
                'db_table': 'commodities',
                'permissions': (('read_commodities', 'Can read commodities supported by platform'),),
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('note_for_country_regulations', models.TextField(db_column='Note_for_country_regulations')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries Supported',
                'db_table': 'countries',
                'permissions': (('read_countries', 'Can read countries supported by platform'),),
            },
        ),
        migrations.CreateModel(
            name='TypeOfParameters',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'TYPE OF MRL PARAMETER',
                'verbose_name_plural': 'TYPES OF MRL PARAMETERS SUPPORTED',
                'db_table': 'type_of_parameters',
                'permissions': (('read_parameter_types', 'Can read parameter types supported by platform'),),
            },
        ),
        migrations.CreateModel(
            name='RegulatoryParameters',
            fields=[
                ('name_of_parameter', models.CharField(db_column='Name_of_parameter', max_length=255, primary_key=True, serialize=False)),
                ('type_of_parameter', models.ForeignKey(db_column='Type_of_parameter', on_delete=django.db.models.deletion.DO_NOTHING, to='ui.TypeOfParameters')),
            ],
            options={
                'verbose_name': 'MRL PARAMETER',
                'verbose_name_plural': 'MRL PARAMETERS SUPPORTED',
                'db_table': 'regulatory_parameters',
                'permissions': (('read_parameters', 'Can read parameters supported by platform'),),
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('ID', models.IntegerField(db_column='IDX', editable=False, primary_key=True, serialize=False)),
                ('mrl', models.CharField(db_column='MRL', max_length=10)),
                ('mrl_type', models.CharField(choices=[('Default', 'Default'), ('General', 'General')], db_column='MRL_type', default='Default', max_length=7)),
                ('effective_date', models.DateField(blank=True, db_column='Effective_Date', null=True)),
                ('expire_date', models.DateField(blank=True, db_column='Expire_Date', null=True)),
                ('status_of_expire_date', models.CharField(blank=True, choices=[('Proposed', 'Proposed'), ('Fixed', 'Fixed')], db_column='Status_of_expire_date', max_length=8, null=True)),
                ('import_tolerance', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('info_on_regulations', models.CharField(blank=True, db_column='Info_on_regulations', max_length=255, null=True)),
                ('residue_definition', models.CharField(blank=True, db_column='Residue_definititon', max_length=200, null=True)),
                ('source_document', models.TextField(blank=True, null=True)),
                ('date_of_publishing_source', models.DateField(blank=True, db_column='Date_of_publishing_source', null=True)),
                ('criticality_of_maintaining', models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('MONITORING', 'MONITORING'), ('DRAFT REGULATIONS', 'DRAFT REGULATIONS')], db_column='Criticality_of_maintaining', default='MANDATORY', max_length=17)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('country', models.ForeignKey(db_column='Country', on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Countries')),
                ('parameter', models.ForeignKey(db_column='Parameter', on_delete=django.db.models.deletion.DO_NOTHING, to='ui.RegulatoryParameters')),
                ('product', models.ForeignKey(db_column='Product', on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Commodities')),
            ],
            options={
                'verbose_name': 'DETAILED MRL PARAMETER',
                'verbose_name_plural': 'Detailed MRL Parameters for specifics',
                'db_table': 'master',
                'permissions': (('read_master', 'Can read specific MRL related to various countries and commodities supported by platform'),),
                'unique_together': {('country', 'product', 'parameter', 'criticality_of_maintaining')},
            },
        ),
        migrations.CreateModel(
            name='ComCountryRelation',
            fields=[
                ('commodity', models.OneToOneField(db_column='commodity', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ui.Commodities')),
                ('published_commodity', models.TextField(blank=True, db_column='Published_commodity', null=True)),
                ('definition_commodity_field', models.TextField(blank=True, db_column='Definition_commodity_', null=True)),
                ('undefined_published_commodity', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], db_column='Undefined_published_commodity', default='NO', max_length=3)),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Countries')),
            ],
            options={
                'verbose_name': 'country and commodity',
                'verbose_name_plural': 'Country commodity rules',
                'db_table': 'com_country_relation',
                'permissions': (('read_Country_product_relationships', 'Can read specific information related to any product with any country'),),
                'unique_together': {('commodity', 'country')},
            },
        ),
    ]
