# Generated by Django 3.0.5 on 2020-05-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comcountryrelation',
            options={'verbose_name': 'country and commodity', 'verbose_name_plural': 'Country commodity rules'},
        ),
        migrations.AlterModelOptions(
            name='commodities',
            options={'verbose_name': 'Commodity', 'verbose_name_plural': 'List of our Commodities'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries Supported'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'DETAILED MRL PARAMETER', 'verbose_name_plural': 'Detailed MRL Parameters for specifics'},
        ),
        migrations.AlterModelOptions(
            name='regulatoryparameters',
            options={'verbose_name': 'MRL PARAMETER', 'verbose_name_plural': 'MRL PARAMETERS SUPPORTED'},
        ),
        migrations.AlterModelOptions(
            name='typeofparameters',
            options={'verbose_name': 'TYPE OF MRL PARAMETER', 'verbose_name_plural': 'TYPES OF MRL PARAMETERS SUPPORTED'},
        ),
    ]
