# Generated by Django 3.0.5 on 2020-05-07 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0003_auto_20200507_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Countries_of_interest', models.ForeignKey(blank=True, db_column='Country', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Countries')),
                ('Parameter_types_of_interest', models.ForeignKey(blank=True, db_column='type', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.TypeOfParameters')),
                ('Parameters_of_interest', models.ForeignKey(blank=True, db_column='parameter', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.RegulatoryParameters')),
                ('Products_of_interest', models.ForeignKey(blank=True, db_column='product', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Commodities')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
