# Generated by Django 3.0.5 on 2020-05-07 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'DETAILED MRL PARAMETER', 'verbose_name_plural': 'To give users access to specific things CLICK HERE'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('Parameter_types_of_interest',), ('Countries_of_interest', 'Products_of_interest', 'Parameters_of_interest')},
        ),
    ]
