# Generated by Django 3.0.5 on 2020-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20200507_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['country', 'product', 'criticality_of_maintaining', 'parameter'], 'verbose_name': 'DETAILED MRL PARAMETER', 'verbose_name_plural': 'Detailed MRL Parameters for specifics'},
        ),
        migrations.RenameField(
            model_name='master',
            old_name='mrl_type',
            new_name='Limit_type',
        ),
        migrations.RemoveField(
            model_name='master',
            name='mrl',
        ),
        migrations.AddField(
            model_name='countries',
            name='pdf_note',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='master',
            name='Maximum_Limit',
            field=models.FloatField(blank=True, db_column='Maximum_Limit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='Minimum_Limit',
            field=models.FloatField(db_column='Minimum_Limit', default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='master',
            name='Unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=10, null=True),
        ),
    ]
