# Generated by Django 3.0.5 on 2020-05-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20200513_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('Authority_Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(blank=True, db_column='Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Countries')),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='Compliance_Authority',
            field=models.ForeignKey(blank=True, db_column='Authority_Name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Authorities'),
        ),
    ]
