# Generated by Django 3.0.5 on 2020-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20200514_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='Unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=20, null=True),
        ),
    ]
