# Generated by Django 3.0.5 on 2020-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_authorities_info_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='Limit_type',
            field=models.CharField(choices=[('Default', 'Default'), ('General', 'General'), ('Organic MRLs', 'Organic MRLs'), ('Not defined', 'Not defined')], db_column='MRL_type', default='Default', max_length=20),
        ),
    ]
