# Generated by Django 3.0.5 on 2020-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_auto_20200514_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='criticality_of_maintaining',
            field=models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('MONITORING', 'MONITORING'), ('DRAFT REGULATIONS', 'DRAFT REGULATIONS'), ('PROPOSED DRAFT', 'PROPOSED DRAFT')], db_column='Criticality_of_maintaining', default='MANDATORY', max_length=20),
        ),
    ]
