# Generated by Django 3.0.5 on 2020-05-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_auto_20200514_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorities',
            options={'verbose_name': 'Authority', 'verbose_name_plural': 'Regulatory Authorities'},
        ),
        migrations.AlterModelOptions(
            name='comcountryrelation',
            options={'verbose_name': 'Country-Product Relationship', 'verbose_name_plural': 'Rules Associated with country and products'},
        ),
        migrations.AlterModelOptions(
            name='commodities',
            options={'verbose_name': 'Commodity', 'verbose_name_plural': 'List of Commodities'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'List of Countries'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['country', 'product', 'criticality_of_maintaining', 'parameter'], 'verbose_name': 'Regulation Detail', 'verbose_name_plural': 'Main Table'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Interest', 'verbose_name_plural': 'USER INTERESTS'},
        ),
        migrations.AlterModelOptions(
            name='regulatoryparameters',
            options={'verbose_name': 'PARAMETER', 'verbose_name_plural': 'List of Parameters'},
        ),
        migrations.AlterModelOptions(
            name='typeofparameters',
            options={'verbose_name': 'TYPE OF MRL PARAMETER', 'verbose_name_plural': 'List of TYPES OF MRL PARAMETERS'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='residue_definition',
        ),
        migrations.AddField(
            model_name='master',
            name='parameter_definition',
            field=models.CharField(blank=True, db_column='Residue_definititon', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='criticality_of_maintaining',
            field=models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('MONITORING', 'MONITORING'), ('PROPOSED DRAFT', 'PROPOSED DRAFT')], db_column='Criticality_of_maintaining', default='MANDATORY', max_length=20),
        ),
    ]
