# Generated by Django 3.0.5 on 2020-05-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_auto_20200515_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofparameters',
            options={'verbose_name': 'TYPE OF PARAMETER', 'verbose_name_plural': 'List of TYPES OF PARAMETERS'},
        ),
    ]
